export EDITOR=vim
export GOPATH=$HOME/.go
export HOMEBREW_NO_ENV_HINTS=true
export HOMEBREW_REQUIRE_TAP_TRUST=1
export JAVA_HOME=/opt/homebrew/opt/openjdk@21
export KUBECTL_EXTERNAL_DIFF=diff-so-fancy
export LC_COLLATE=C
export LESSHISTFILE=-
