#!/bin/bash

set -euo pipefail

touch "$HOME/.kube/gke-auth-cache.ts"
if [[ ! $HOME/.kube/gke-auth-cache.ts -ot $HOME/.kube/gke-auth-cache ]]; then
    TOKEN=$(gcloud auth print-access-token)
    EXPIRY=$(curl -sf --oauth2-bearer "$TOKEN" https://oauth2.googleapis.com/tokeninfo | jq -r '.exp | tonumber | todate')
    cat > "$HOME/.kube/gke-auth-cache" << END
kind: ExecCredential
apiVersion: client.authentication.k8s.io/v1
spec:
  interactive: false
status:
  expirationTimestamp: "$EXPIRY"
  token: "$TOKEN"
END
    touch -d "$EXPIRY" "$HOME/.kube/gke-auth-cache"
fi
cat "$HOME/.kube/gke-auth-cache"
